/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dbguiapp;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 * Java GUI application that allows the user to perform tasks on the books database.
 *
 * @author Timothy Bradford
 */
public class DBGUI extends javax.swing.JFrame {

    final String DATABASE_URL = "jdbc:derby://localhost:1527/books";
    final String qInsertAuth = "INSERT INTO Authors (FirstName, LastName) VALUES ('Sue', 'Red')";
    ArrayList<String> aNames = new ArrayList<>();
    Connection connection;

    /**
     * Creates new form DBGUI
     */
    public DBGUI() {
        initComponents();

        try {
            this.connection = DriverManager.getConnection(DATABASE_URL, "deitel", "deitel");
            getAuthorsList();
        } // AutoCloseable objects' close methods are called now  // AutoCloseable objects' close methods are called now 
        catch (SQLException sqlException) {
            sqlException.printStackTrace();
        }

    }

    private void executeQuery(String query) throws SQLException {
        //Connect to the DataBase
        //Connection connection = DriverManager.getConnection(DATABASE_URL, "deitel", "deitel");
        //Execute Queries
        this.connection.createStatement().executeQuery(query);
    }

    private void getAuthorsList() throws SQLException {
        //Connect to the DataBase
        // connection = DriverManager.getConnection(DATABASE_URL, "deitel", "deitel");

        //Execute Querie
        ResultSet rs = this.connection.createStatement().executeQuery("SELECT FIRSTNAME, LASTNAME, AUTHORID FROM authors ORDER BY AUTHORID");
        cboxP2.removeAllItems();
        cboxP3.removeAllItems();

        while (rs.next()) {
            cboxP2.addItem(new Author(rs.getString("FIRSTNAME"), rs.getString("LASTNAME"), rs.getInt("AUTHORID")));
            cboxP3.addItem(new Author(rs.getString("FIRSTNAME"), rs.getString("LASTNAME"), rs.getInt("AUTHORID")));
        }

    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        btnAddAthorP1 = new javax.swing.JButton();
        txLNameP1 = new javax.swing.JTextField();
        txFNameP1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnEditAuthP2 = new javax.swing.JButton();
        cboxP2 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txLNameP2 = new javax.swing.JTextField();
        txFNameP2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnAddTitleP3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        cboxP3 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txISBNP3 = new javax.swing.JTextField();
        txTitleP3 = new javax.swing.JTextField();
        txCRYP3 = new javax.swing.JTextField();
        txENP3 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setToolTipText("");
        jTabbedPane1.setDoubleBuffered(true);

        btnAddAthorP1.setText("Add Author");
        btnAddAthorP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAthorP1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Author's First Name");

        jLabel2.setText("Author's Last Name");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAddAthorP1)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(txFNameP1, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                    .addComponent(txLNameP1)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAddAthorP1)
                .addGap(7, 7, 7)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txFNameP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txLNameP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Add New Author", jPanel1);

        btnEditAuthP2.setText("Edit Author");
        btnEditAuthP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditAuthP2ActionPerformed(evt);
            }
        });

        cboxP2.setMaximumRowCount(100);

        jLabel3.setText("The author that you want to edit =>>");

        jLabel4.setText("New Last Name");

        jLabel5.setText("New First Name");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnEditAuthP2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboxP2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txFNameP2)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(0, 195, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(txLNameP2, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditAuthP2)
                    .addComponent(cboxP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txFNameP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txLNameP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Edit Existing Author", jPanel2);

        btnAddTitleP3.setText("Add Title");
        btnAddTitleP3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddTitleP3ActionPerformed(evt);
            }
        });

        jLabel6.setText("The author for the new title =>>");

        cboxP3.setMaximumRowCount(100);
        cboxP3.setToolTipText("");

        jLabel7.setText("Title");

        jLabel8.setText("ISBN");

        jLabel9.setText("Edition Number");

        jLabel10.setText("Copy Right Year");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(btnAddTitleP3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel6))
                        .addComponent(txTitleP3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(cboxP3, 0, 347, Short.MAX_VALUE)
                        .addGap(21, 21, 21))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txISBNP3, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(txENP3, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txCRYP3, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddTitleP3)
                    .addComponent(cboxP3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txTitleP3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txISBNP3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txENP3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txCRYP3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Add New Title", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Add New Author");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * this will add new authors to the authors table.
     *
     * @param evt
     */
    private void btnAddAthorP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAthorP1ActionPerformed
        if (txFNameP1.getText().length() > 0 && txLNameP1.getText().length() > 0) {
            try {
                this.connection.createStatement().executeUpdate("INSERT INTO Authors (FirstName, LastName) VALUES ('" + txFNameP1.getText() + "', '" + txLNameP1.getText() + "')");
                JOptionPane.showMessageDialog(null, "The author " + txFNameP1.getText() + ", " + txLNameP1.getText() + " has been added successfully", null, JOptionPane.INFORMATION_MESSAGE);
            } catch (SQLException sqlException) {
                JOptionPane.showMessageDialog(null, "uh oh, something went wrong.", null, JOptionPane.ERROR_MESSAGE);
                sqlException.printStackTrace();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please add a valid first and last name for the author", null, JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAddAthorP1ActionPerformed

    /**
     * Edit the existing information for an author.
     *
     * @param evt
     */
    private void btnEditAuthP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditAuthP2ActionPerformed
        //make sure there is an author selected
        if (cboxP2.getItemAt(cboxP2.getSelectedIndex()) != null) {
            //Create vars for better redability
            String FirstName = cboxP2.getItemAt(cboxP2.getSelectedIndex()).getfName();
            String LastName = cboxP2.getItemAt(cboxP2.getSelectedIndex()).getlName();
            int ID = cboxP2.getItemAt(cboxP2.getSelectedIndex()).getId();

            //check user input and add any changes...
            if (txFNameP2.getText().length() > 0) {
                FirstName = txFNameP2.getText();
            }

            if (txLNameP2.getText().length() > 0) {
                LastName = txLNameP2.getText();
            }

            //Create sql statment
            String sql = "UPDATE Authors SET FirstName = '" + FirstName + "', LastName = '" + LastName + "' WHERE authorid = " + ID;

            try {
                //update data base
                this.connection.createStatement().executeUpdate(sql);
                //update the combo boxes with what is in the data base
                getAuthorsList();
                //notify user of completion
                JOptionPane.showMessageDialog(null, "The author " + txFNameP1.getText() + ", " + txLNameP1.getText() + " has been added successfully", null, JOptionPane.INFORMATION_MESSAGE);
            } catch (SQLException sqlException) {
                //let user know of this did not work
                JOptionPane.showMessageDialog(null, "uh oh, something went wrong.", null, JOptionPane.ERROR_MESSAGE);
                sqlException.printStackTrace();
            }
        } else {
            //notify user they need to select author
            JOptionPane.showMessageDialog(null, "Please select author", null, JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEditAuthP2ActionPerformed

    /**
     * Add a new title for an author. (Remember that the book must have an entry in the AuthorISBN table).
     *
     * @param evt
     */
    private void btnAddTitleP3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddTitleP3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddTitleP3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DBGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DBGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DBGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DBGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DBGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddAthorP1;
    private javax.swing.JButton btnAddTitleP3;
    private javax.swing.JButton btnEditAuthP2;
    private javax.swing.JComboBox<Author> cboxP2;
    private javax.swing.JComboBox<Author> cboxP3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField txCRYP3;
    private javax.swing.JTextField txENP3;
    private javax.swing.JTextField txFNameP1;
    private javax.swing.JTextField txFNameP2;
    private javax.swing.JTextField txISBNP3;
    private javax.swing.JTextField txLNameP1;
    private javax.swing.JTextField txLNameP2;
    private javax.swing.JTextField txTitleP3;
    // End of variables declaration//GEN-END:variables
}
